- package.json
> Move some packages into dev deps

- index.js
- lib/swim.js
- package.json
- test/integration/admin_join_test.js
- test/integration/index.js
It currently only warns when it should really fail.
reviewers: @jwolski
cc: @sh1mmer
> Make adminJoin fail harder.

- index.js
- test/lib/alloc-ringpop.js
- test/ringpop_alloc_error_test.js
reviewers: @jwolski
cc: @sh1mmer
> gaurd against invalid app

- .travis.yml
- package.json
> Travis CI integration

- benchmarks/bench_ringpop_stat_cached_keys.js
- benchmarks/bench_ringpop_stat_new_keys.js
- index.js
- lib/members.js
- lib/request-proxy.js
- test/mock/request-proxy.js
- test/mock/tchannel.js
- test/proxy_req_test.js
- test/request_proxy_test.js
This is a breaking change required for serial processing
@Raynos
> Add key used on lookup to head transmitted through proxy and emit head too

- index.js
- lib/debug-log-logger.js
- lib/nulls.js
- lib/request-proxy.js
- lib/swim.js
- test/mock/logger.js
reviewer: @jwolski
cc @sh1mmer
> Add a bunch of proxying logging.

- index.js
- test/index_test.js
> handleOrProxy opts arg is not required

- lib/request-proxy.js
- package.json
> Use body caching

- index.js
- lib/request-proxy.js
- test/proxy_req_test.js
- test/request_proxy_test.js
* Renames ringpopKey to ringpopKeys
* Makes ringpopKeys an array of strings instead of a single string
* Renames checksum to ringpopChecksum
@jwolski @Raynos
> Make ringpopKeys an array

- package.json
> Upgrades to body@5.0.0

- index.js
- package.json
- test/integration/handle_or_proxy_test.js
- test/lib/alloc-cluster.js
Takes a request with multiple keys and fans it out to all the destinations responsible
@jwolski @Raynos
> Handle or proxy all

- index.js
- lib/errors.js
- test/index_test.js
@jmccarthy14 @Raynos This'll allow ringpop serial to return stats over the ringpop /admin/stats endpoint
> Allow stats hooks to be registered for ringpop extensions

- index.js
- test/integration/handle_or_proxy_test.js
- test/lib/alloc-cluster.js
> Simplifies handleOrProxyAll interface by making it async instead of sync

- index.js
- test/integration/handle_or_proxy_test.js
> Remove localHandler in favor of emitting an event

- index.js
- lib/request-proxy-util.js
- lib/request-proxy.js
- test/integration/proxy_req_test.js
- test/integration/request_proxy_test.js
- test/lib/alloc-cluster.js
@Raynos @markyen This will allow proxy requests to override the proxy endpoint.
> Request proxy endpoint override

- lib/request-proxy.js
> Include local instance address for proxy request logging

- lib/membership_update_rollup.js
> Add timestamps to membership update rollups

- lib/join_cluster.js
TChannel v2 only accepts strings and buffers. We need to
JSON stringify outside of tchannel.
reviewers: @jcorbin @jwolski
> support tchannel v2

- lib/members.js
- lib/rbtree.js
- lib/swim.js
- package.json
There's still some work to do to get all files in the repo to jshint correctly. I'll start with lib/.
@Raynos
> JSHint the lib/ directory

- index.js
- lib/swim/join-sender.js
- test/join-sender-test.js
Last of the minor refactor branches that are part damping work.
Aligning send joins with rest of operations!
@Raynos
> Rename join_cluster to fit sender/recvr pattern that is unfolding

- index.js
- lib/errors.js
- lib/swim/join-recvr.js
- lib/tchannel.js
- test/index_test.js
- test/integration/join-test.js
Another refactor ahead of damping. Trying to make send/recv pattern uniform across the board. No logic change here. Just moving code.
@Raynos
> Factor out protocol join from Ringpop ahead of damping

- index.js
- lib/admin-join-recvr.js
- lib/proxy-req-recvr.js
- lib/swim/join-sender.js
- lib/swim/ping-recvr.js
- lib/tchannel.js
- test/index_test.js
- test/join-sender-test.js
Continue digging out all the things that should not be hanging off the Ringpop prototype.
@Raynos
> Reduce footprint of Ringpop's index.js by extracting endpoint handlers

- lib/membership.js
> Removing unused argumnet provided to getJoinPosition function

- lib/swim/join-sender.js
> Reduce logging levels during join

- lib/swim/ping-req-sender.js
We have a few of these left and they make log analysis difficult.
r: @jwolski @rf
> remove dynamic log messages

- lib/request-proxy/send.js
> Send stat emitted for request proxying

- README.md
Fixed the link in README.md to point to the original SWIM paper
> Fix link to SWIM paper

- index.js
> Allow parallelism factor for join to be passed through bootstrap()

- benchmarks/large-membership-update.js
- benchmarks/large-membership.json
- benchmarks/run.js
Sample output:
```
$ node benchmarks/run.js -f benchmarks/large-membership-update.js -r 4e5b8b990fd1652e8b2b7d8a0ef9f50ec7dd52e9~..HEAD
Running 4 benchmark(s) for benchmarks/large-membership-update.js
4e5b8b9 Large membership benchmark 80.30 ops/sec
dd2d3fc Index members by their address 5,091 ops/sec
9e93d77 Batch updates to ring 5,026 ops/sec
462f65b Simple benchmark runner 4,891 ops/sec
Benchmark complete!
```
> Benchmark for large membership updates and benchmark runner

- benchmarks/compute-checksum.js
- lib/membership.js
```
Running 2 benchmark(s) for benchmarks/compute-checksum.js
a7ad86f Membership compute checksum benchmark 676 ops/sec
ea0c271 Favor string concatenation over join() 1,706 ops/sec
Benchmark complete!
```
> Faster compute checksum

- index.js
- lib/request-proxy/index.js
- lib/request-proxy/send.js
- lib/swim/join-sender.js
- lib/swim/ping-req-sender.js
- lib/swim/ping-sender.js
- lib/tchannel.js
- main.js
- package.json
- scripts/generate-hosts.js
- scripts/tick-cluster.js
- test/integration/join-test.js
- test/integration/proxy-test.js
- test/integration/swim-test.js
- test/lib/alloc-ringpop.js
- test/lib/bootstrap.js
- test/lib/test-ringpop-cluster.js
- test/mock/channel.js
- test/mock/tchannel.js
- test/request_proxy_test.js
All of the features.
r: @jwolski
> Upgrade tchannel @ 2.0.0

- lib/swim/suspicion.js
- test/swim_test.js
This was flappy. Now it's not.
@Raynos @kriskowal @danielheller
> Fix flappy suspicion period test

- index.js
- lib/util.js
CC @jwolski 
Changes added on top of latest version of master branch: 
/admin/stats now returns additional stats: TChannel version, Ringpop version, uptime, and timestamp
> Ringpop add version to latest

- lib/dissemination.js
- lib/membership.js
- lib/swim/suspicion.js
- package.json
This will make traceability of how changes originate, how many hops they make, and when the last time they are applied, and who the last node was that applied it.
> Add ID to change that is disseminated over gossip

- docs/running_ringpop.md
Here's a first draft of the `Running with tick-cluster section`. Let me know what you think.
@davejn
> Documentation for Running with tick-cluster section

- lib/swim/ping-req-sender.js
> Reduce log level of ping-req confirming unreachable member

- index.js
- lib/ring.js
- test/ring-test.js
@jwolski Can you take a look when you get a chance?
> lookupN: a function that returns the 'preference list' for a given key

- benchmarks/convergence-time/scenario-runner.js
- benchmarks/convergence-time/scenarios/half-cluster-failure.js
- benchmarks/convergence-time/scenarios/single-node-failure.js
- benchmarks/convergence-time/worker.js
- benchmarks/lib/runner.js
- index.js
- package.json
benchmark convergence time with child process & message passing
future work includes
- replacing interprocess messaging with swim/ringpop cli over tchannel
- worker publish checksum on membership update to independent channel instead of interprocess messaging and master/admin watch for divergence & convergence to compute convergence time; which may apply to production as well
will parameterize benchmark after #53 and other cleanup work
> benchmark convergence time

- benchmarks/convergence-time/worker.js
- index.js
> not to expose membership functions

- index.js
- lib/request-proxy/index.js
- test/integration/proxy-test.js
- test/lib/alloc-ringpop.js
cc @jwolski @iproctor @markyen
> add option to allow inconsistency in request proxy

- lib/request-proxy/index.js
- package.json
I can't imagine this is helping Ringpop any either: https://github.com/uber/tchannel/pull/1179. 
@Raynos @jcorbin
> Remove readable-stream dep

- index.js
- lib/ring.js
Quick addition to stats to provide ring checksum in addition to servers.
@Alexhauser23 is this going to break anything in UI?
@CorgiMan @danielheller @benfleis
> Add checksum to ring stats

- client.js
- config.js
- server/admin/config.js
- server/admin/index.js
- test/integration/admin_test.js
- test/unit/server/admin/config_test.js
Admin endpoints that allow you to change config dynamically. Implementation-wise this is pretty done. I'll add a couple of integration tests.
This functionality is not immediately needed, but was a fun Friday evening project before I went home. And this'll give us a reason to add `ringpop-admin config` commands. Have a nice weekend! 
@danielheller @CorgiMan @benfleis
> /admin/config/set and /admin/config/get endpoints

- index.js
> Reduce prototype footprint; de-extract validateProps

- client.js
This ones a tough one ;P. More incidental cleanup from damping subprotocol work.
@uber/ringpop
> Add a space

- README.md
> Update w/ a better intro and example

- main.js
- package.json
tick-cluster is broken when using the TChannel version greater than 2.8.1. Use listen on TChannel obj.
@thanodnl @benfleis @danielheller @mbrysa
> Update main.js after TChannel breaking (?) changes

- lib/swim/gossip.js
- server/admin/gossip.js
Added a /admin/gossip/status endpoint which'll be useful to determine if the gossip protocol has truly stopped for damped members
@uber/ringpop
> An /admin/gossip/status endpoint

- lib/dissemination.js
Incidental cleanup for upcoming PR.
@uber/ringpop
> Make _issueAt part of prototype

- index.js
e.g., jump consistent hash ring, Hilbert ring…
https://en.wikipedia.org/wiki/Hilbert_curve
r @jwolski
> Permit alternate ring implementation

- docs/architecture_design.md
- lib/membership/index.js
a bit of doc, and s/local/id/ on the struct. also added 'address' to the struct, future facing.
@wolski @CorgiMan
> add tracing docs, and fix actual event struct

- config.js
- index.js
- lib/membership/index.js
- lib/ring/index.js
- main.js
fingerprint is platform independent: https://github.com/lovell/farmhash#fingerprint.
Looks like TChannel ran into the same issue: https://github.com/uber/tchannel-node/commit/44a7edbb1facc9f53b29633820a4d7afbb03dc2d
/cc @uber/ringpop
> Use fingerprint32 over hash32.

- config.js
- lib/on_membership_event.js
@uber/ringpop @markyen @weikai77
> Disable membership update rollup reporting by default

- examples/README.md
- examples/cluster.js
- examples/handle_or_forward.js
- examples/key_value.js
- examples/leader_election.js
- examples/parse_args.js
- examples/safe_parse.js
- package.json
Example code used for Ringpop workshop.
@uber/ringpop
> Leader election and key value examples with README

- lib/request-proxy/index.js
Add stats to track the number of inflight forwarded requests.
@uber/ringpop
> Track number of inflight forwarded requests

- main.js
Script has the executable bit set but missing interpreter at the top.
> Fix missing shebang in main.js

- config.js
- lib/logging/logger_factory.js
- lib/membership/member.js
Easy one. Change damp score logging so that its controlled by module loggers.
@uber/ringpop
> Add a damping logger for flap damping logging

- index.js
As the title says...
@uber/ringpop
> Stat for lookup timing

- lib/membership/member.js
As the title says...
@uber/ringpop
> Stat to track refuted updates by local member

- lib/on_ring_event.js
- package.json
Send ring.changed to Graphite.
@uber/ringpop
> Ring changed stat

- README.md
- client.js
- docs/programming_ringpop.md
- examples/cluster.js
- examples/tchannel-forwarding.js
- main.js
- scripts/tick-cluster.js
- test/lib/alloc-ringpop.js
- test/lib/tchannel-proxy-cluster.js
- test/lib/test-ringpop-cluster.js
Set the trace param to false for Ringpop documentation, README, tick-cluster, all-the-things.
@Raynos @benfleis
> Specify trace param to TChannel makeSubChannel

- lib/gossip/dissemination.js
- lib/on_membership_event.js
- test/integration/join-test.js
Reopened against master.
@uber/ringpop
> Don't disseminate join list

- lib/errors.js
- lib/gossip/events.js
- lib/gossip/index.js
- lib/gossip/ping-req-sender.js
- lib/gossip/ping-sender.js
- server/protocol/ping-req.js
- server/protocol/ping.js
- test/integration/join-test.js
- test/integration/not-ready-test.js
- test/lib/alloc-ringpop.js
- test/lib/test-ringpop-cluster.js
> Refuse protocol communication until ready

- index.js
- lib/errors.js
- lib/util.js
- test/unit/index-test.js
- test/unit/ringpop_alloc_error_test.js
…invalid host-port as the source field
> Cleanup from previous PR

- config.js
- lib/logging/logger_factory.js
- lib/membership/events.js
- lib/membership/index.js
- lib/on_membership_event.js
- lib/on_ring_event.js
- lib/ring/events.js
- lib/ring/index.js
Helps us to measure convergence
@uber/ringpop
> Log membership and ring checksum computed events

- lib/gossip/damper.js
- lib/gossip/dissemination.js
- lib/gossip/ping-req-sender.js
- lib/gossip/ping-sender.js
- lib/membership/index.js
- request_response.js
- test/integration/index.js
- test/integration/piggyback-test.js
Not ready for review yet, only want to see if it passes the tests
> only raise piggyback count if ping is succesfull

- README.md
- scripts/tick-cluster.js
* Prepare ringpop for development.
* Update the max open file limit (needed in default settings of OSX).
* Introduce tick-cluster to the README.
> Update README for newbies

- README.md
> add travis badge to README.md

- index.js
- lib/gossip/dissemination.js
- server/protocol/ping-req.js
- server/protocol/ping.js
- test/integration/bidirectional-full-sync-test.js
- test/unit/dissemination-test.js
This is a port of the bi-direcitonal full syncs feature in ringpop-go.
> Bi-directional full syncs

- client.js
- client_request.js
- index.js
- lib/middleware/index.js
- lib/middleware/stack.js
- lib/middleware/tombstone.js
- lib/middleware/transport.js
- server/admin/config.js
- server/admin/gossip.js
- server/admin/member.js
- server/admin/reload.js
- server/admin/stats.js
- server/index.js
- server/protocol/damp_req.js
- server/protocol/join.js
- server/protocol/ping-req.js
- server/protocol/ping.js
- server/proxy-req.js
- server/trace.js
- test/unit/index-test.js
- test/unit/middleware_test.js
- test/unit/server/admin/config_test.js
- test/unit/server/protocol/damp_req_test.js
- test/unit/server/protocol/join_test.js
- test/unit/transport_test.js
This is #250 which I closed by mistake.
> Add server/client middleware to patch tombstone state

- lib/membership/index.js
- lib/membership/member.js
- test/unit/member_status_test.js
In preparation of partition healing we need a method to check if a status is considered pingable.
> Refactor MemberShip~isPingable(member)

- lib/membership/member.js
- test/unit/index-test.js
- test/unit/member_status_test.js
Based on the #259 to prevent merge-conflicts.
> Simplify override logic during updates

- config.js
- index.js
- lib/partition_healing/discover_provider_healer.js
- lib/partition_healing/healer.js
- lib/partition_healing/index.js
- server/admin/index.js
- server/admin/partition-healing.js
- test/integration/gossip_test.js
- test/integration/partition_healing_test.js
- test/lib/gossip-utils.js
- test/lib/test-ringpop-cluster.js
- test/run-shared-integration-tests
- test/unit/discover_provider_healer_test.js
- test/unit/server/admin/partition_healing_test.js
This PR adds partition healing to ringpop-node. This initial PR is only healing manually. Periodic partition healing will be added in a subsequent PR.
> Partition healing

- lib/partition_healing/discover_provider_healer.js
Previous value was heal.triggered.discover_provider. Changing it to be in sync with ringpop-go.
> Change emitted stat name to heal.triggered

- index.js
Related documentation addition: https://github.com/uber/ringpop-common/pull/71
> Emit lookupN timing event

- test/unit/membership_test.js
Wolski says it ought to be removed.
Thanks Abhijeet Mohan <void.aby@gmail.com> for bringing this to our attention
> Remove dead code

- .travis.yml
- config.js
- index.js
- lib/lag_sampler.js
- lib/request-proxy/index.js
- lib/ring/index.js
- main.js
- package.json
- test/lib/alloc-request.js
- test/lib/alloc-response.js
- test/run-shared-integration-tests
This PR has been tested in the production rt-supply service.
This PR contains all the work by @sashahilton00
r: @thanodnl @Motiejus
> Add node4 support

- CHANGES.md
In preparation for the new release this will add the changes to the changelog.
> add changes to changelog for release of 10.16.0

- config.js
- lib/self-evict.js
- test/unit/self-evict-test.js
Ping other members on self-eviction.
This PR is dependent on #299
> [self-evict 2] Gossip self eviction

- main.js
- test/run-shared-integration-tests
Let testpop `selfEvict` on `ctrl+c` (`SIGINT`).
> [self-evict 3] self evict on shutdown in testpop

- discover-providers.js
- lib/backoff.js
- package.json
- test/integration/discover-provider-retry-test.js
- test/integration/index.js
- test/lib/test-ringpop-cluster.js
- test/unit/backoff_test.js
- test/unit/discover-providers-test.js
Support retrying the discover provider if it returns an error or if it does not return valid results.
> Retry discover provider

- CHANGES.md
Adding release notes for ringpop 10.18.0
> 10.18.0 release notes

- .travis.yml
- index.js
- lib/gossip/ping-sender.js
- server/protocol/ping.js
- test/integration/gossip_test.js
Always reject pings from wrong app name
> Add option to enforce identical app name in pings
