uber-node/ringpop-node

lib/request-proxy.js
package.json
test/lib/alloc-request.js
test/lib/alloc-response.js

Without `hammock` in dependencies, `require('ringpop')`
just fails.
I had to fork hammock because reasons.
reviewers: @jwolski
cc: @sh1mmer

add hammock to dependencies

---

index.js
lib/members.js
lib/swim.js
lib/tchannel.js
test/index_test.js
test/members_test.js
test/mock/membership.js
test/mock/noop.js
test/swim_test.js

Excuse all the churn here. 
The operation implemented is an /admin/leave which sets the local member status to leave and then disseminated to the protocol pingers. This operation is manual much like /admin/join. When a member is in the 'leave' status, the member is soft-removed from membership. It'll be removed from pingers lists and the ring itself. As part of the 'leave' operation, local gossip and suspect protocol are stopped. A member that has previously left can rejoin by /admin/join.
As part of this work I refactored and took the start/stop of gossip and suspicion subprotocol out into the lib/swim.js file. I think I left this code slightly better than it was. Still lots of room for improvement.
There's also a relatively high amount of test coverage here... which is good
@mranney …

Implement admin leave

---

lib/members.js
test/members_test.js

While unlikely that suspect hasn't made its way around the cluster, given the 5s suspect period timeout, this will help fault detection in the event that a faulty member has been detected before suspect status has reached all nodes.
@mranney @mrhooray @Raynos

Faulty overrides alive member with same incarnation number

---

README.md
index.js
lib/members.js
test/index_test.js

This change is necessary for the sevnups of the world that are looking to take action when ring-state changes (node added/removed). The problem today is that ringpop will fire events for both membership changes and ring changes under the same name causing sevnup to rescan the vnode-space for membership updates like when node are suspected. This is not a huge problem, but splitting events improves correctness.
@iproctor @Raynos @jmccarthy14

Split changed event into two: membershipChanged and ringChanged

---

README.md
index.js
lib/request-proxy.js
test/integration/proxy_req_test.js
test/integration/request_proxy_test.js
test/lib/alloc-cluster.js
test/lib/alloc-ringpop.js
test/mock/request-proxy.js
test/request_proxy_test.js

Proxied requests suffer from cluster inconsistencies on deploys and what not. Build retries w/ backoff into the request proxying layer to deal with an eventually convergent ring. @Raynos recommended I use a module for backoff, but I decided against it due to the simplicity of the approach below. Feel free to feedback.
@Raynos @jmccarthy14 @mranney @jsu1212 @jcorbin

Request proxy retries

---

lib/swim.js
lib/tchannel.js

Tchannel v1 expects to get an object, string or buffer.
Tchannel v2 expects a string or buffer.
If you pass an object to tchannel v1 it will stringify it
for you. We should stringify it explicitely in ringpop so
that ringpop works with either v1 or v2.
reviewers: @jwolski @jcorbin
cc: @jsu1212

Stringify our bodies and responses for tchannel.

---

main.js

The --hosts argument is required, but its value is then ignored. It probably works out most of the time, since the default value of ./hosts.json is there. Still, a bug.
Tested with a seed hosts file value of "hosts1.json". Before fix, main barfs looking for "./hosts.json". 
Works as expected after fix.
Unit tests pass (as per git hooks)

fix: don't ignore --hosts command line argument value

---

lib/member.js
lib/members.js
test/lib/test-ringpop.js
test/local-incarnation-test.js

Without having a lower bound on the incarnation number, it causes cluster to disseminate more changes than necessary. During a deploy, nodes that detect suspects are disseminating that info throughout the cluster eventually arriving at the original suspect once restarted. When applying the change at that member, incarnation number is bumped a bunch of times until the ring converges. This is apparent in the membership update rollups recently introduced:
```
fields.updates_.10.30.11.2:20801_	  	{"type":"suspect","address":"10.30.11.2:20801","status":"suspect","incarnationNumber":1424847893496,"isLocal":false}, {"type":"alive","address":"10.30.11.2:20801","status":"alive","incarnationNumber":1425346015439,"isLocal":false}, {"type":"alive","address":"10.30.11.2:20801","status":"alive","incarna …
```

Introduce lower bound on incarnation number for local member asserting its aliveness

---

index.js
lib/members.js
lib/ring.js
test/index_test.js
test/members_test.js

This is a nasty bug in ringpop. Ringpop will assume that the update type is `alive` no matter what the status of the member is at the time they're added into the membership list.
@Raynos @iproctor @sunweik @robskillington @leizha

Do not assume update type for first time member

---

lib/swim.js

In preparation for flap damping, I need to fix how ping-req's are currently handled. Amidst that minor rewrite, I stumbled upon this lovely bug. `checksum` was never passed to /protocol/ping-req even though it's a required field. What would happen is that for any ping that would fail, the member would be immediately deemed a suspect regardless of whether the chosen ping-req members could reach the node or not. This usually wasn't spotted because when most pings fail, the member is indeed being restarted or crashed or otherwise. For those transient ping failures, this bug would cause unintended membership changes, from suspect then quickly back to alive.
This could have easily been caught by integration tests. And, good news, they are coming with the aforementioned minor ping-req rewrite. …

Send over checksum with /protocol/ping-req

---

index.js
lib/request-proxy-util.js
lib/request-proxy.js
test/integration/proxy_req_test.js

@jwolski @Raynos 
This is done so that when a request is handled locally, the downstream handler is able to see and use the keys.
I could also duplicate the keys in both headers in order to avoid a breaking change, if we think that's better.

Always pass head object when emitting 'request' event

---

README.md
index.js
lib/request-proxy/index.js
lib/request-proxy/send.js
lib/ring.js
test/hashring_test.js
test/integration/proxy_req_test.js
test/integration/request_proxy_test.js

We currently compare checksums before serving a proxied request. This is generally good practice because you don't want either ends of the request to disagree on the state of the ring. But, in fact, we are comparing the consistency of membership checksums which include status and incarnation number values which really should have no impact on ring lookups other than if one of the nodes were actually removed from or added to the ring. Therefore, we're introducing a ring checksum too. This should prevent a lot of unnecessary invalid checksum errors when the ring shakes up a bit because of suspect statuses
Fixes #55
@mranney @Raynos @mrhooray

Compute a different checksum for the ring and use it for request proxying

---

index.js
lib/swim/ping-req-recvr.js
lib/swim/ping-req-sender.js
lib/tchannel.js
package.json
test/integration/join-test.js
test/integration/swim-test.js
test/lib/test-ringpop-cluster.js

This work is precursor to flap damping. Ping-req's needed to work better.
When nodeA pings nodeB and ping fails, nodeA initiates ping-req to `pingReqSize` random other members: nodeC, nodeD, nodeE. It's each of their responsibilities to ping nodeB on nodeA's behalf. This is known as an indirect ping. When nodeA pings the selected ping-req members (let's say nodeC), one of two things can happen:
1) nodeA cannot reach ping-req member nodeC
2) nodeA reaches nodeC, nodeC cannot reach nodeB.
The first of these two should not count against nodeB. This comes into play in flap damping in the following way. Let's say, nodeB is the flappy one and nodeA damp score for nodeB is nearing the damping threshold. Pings and ping-reqs to nodeB are failing. Every once and a while nodeB responds. It's acting …

Ping-req uses only ping status from unreachable member to initiate suspect period

---

index.js
lib/swim/ping-req-recvr.js
lib/swim/ping-sender.js

As the title states, a minor refactor to sending pings ahead of damping. This is just moving code around and making the send/recv pattern more uniform across gossiping.
@Raynos

Minor refactor to sending pings ahead of damping

---

index.js
lib/membership.js
lib/swim/gossip.js
lib/swim/join-sender.js
lib/swim/suspicion.js
test/lib/test-ringpop.js
test/mock/membership.js
test/swim_test.js

@Raynos This is the bug you ran into. We're trying to access localMember in places where it may not have been added yet (aka not bootstrapping). We can just as easily access ringpop's hostPort for the same value.
More validation needs to be added around what things should be possible if you've not yet bootstrapped ringpop, but i'll leave that for another PR.
I also rewrote most of the suspicion tests in this PR because they were originally poorly written.

Remove dependency on local member

---

README.md
index.js

@Raynos Allow ringpop clients to record lookup times. Moving away from the model where ringpop has statsd dependency.

Lookup time

---

lib/swim/join-sender.js

We currently retry joining as hard as we can; in certain
edge cases I've seen it join 600 times in a row.
We should have a cap on it.
I've also added a fixed backoff of 100ms on every join
attempt to give the network some space to breath.
r: @jwolski @kriskowal

swim/join: Abort the join process if attempts exceeded

---

lib/request-proxy/send.js
test/integration/proxy-test.js

Destinations were not deduped properly after a proxied request failed and thus would not be retried even if the lookup resulted in a single destination (w/ the same value)
@markyen @Raynos

Dedupe multiple destinations on key lookups after failed proxy

---

lib/request-proxy/send.js
test/integration/proxy-test.js

Lei found a problem while load testing. If no retries are specified, there's a chance that we can run into an error of this kind: `TypeError: Cannot call method 'destroy' of undefined` if the socket errors out in the context of writing to the socket for a forwarded request.
@Raynos @leizha

Prevent zalgo bomb on bad socket while forwarding request

---

benchmarks/find-member-by-address.js
lib/membership.js
test/integration/swim-test.js

Trying to go piece-meal with my membership speed-ups. Quick fix to index members by their address for faster access:
```
Running 2 benchmark(s) for benchmarks/find-member-by-address.js
606d65c Benchmark for finding member by address 73,264 ops/sec
3731aff Index members by address 26,864,034 ops/sec
Benchmark complete!
```
@markyen @Raynos

Index by address

---

lib/swim/ping-req-sender.js

This ping-req is reachable message is expected behaviour and
should not be an info(). It creates a bunch of un-needed
background noise.
r: @jwolski

downgrade normal path message to debug

---

benchmarks/add-remove-hashring.js
index.js
lib/membership-update-listener.js
lib/ring.js
test/ring-test.js

This is an effort to improve bootstrap/startup/join times. Bit of a performance boost with a slight refactor to take membership update handling out of the Ringpop prototype.
```
➜  ringpop git:(add-remove-ring-servers)        node benchmarks/add-remove-hashring.js
add/remove 1000 servers individually x 0.97 ops/sec ±2.57% (7 runs sampled)
add/remove 1000 servers in bulk x 3.80 ops/sec ±4.26% (14 runs sampled)
```

Add remove ring servers

---

lib/request-proxy/index.js
package.json
test/integration/proxy-test.js
test/lib/alloc-cluster.js

Resurrecting an old branch that was never put into play. Allows custom limit to body that is proxied across tchannel. By default, limit is 1MB. Lei needs MORE MBs.
This is broken against ringpop master (w/ tchannel v2), but not against latest stable, v9.8.17.
@leizha

Allow body limit to be specified for large object payloads

---

benchmarks/join-response-merge.js
lib/member.js
lib/swim/join-recvr.js
lib/swim/join-response-merge.js
lib/swim/join-sender.js
test/join-response-merge-test.js

This is a pretty significant improvement to the join process, especially when clusters are large (1k+ nodes). Rather than applying individual membership updates for each join response, they are aggregated, merged and applied once after the number of required nodes have been joined. This will reduce a lot of duplicate effort which typically causes significant CPU burn.

Stash join responses

---

index.js

Quick fix. Call to `membership.update()` when ping response is received was redundant -- already done within `ping-sender.js`. This hints at the fact that the `pingMemberNow()` hanging off of the Ringpop prototype shouldn't even exist (just adds complexity and fragmentation of logic) and folded into the logic of PingSender... which is a refactor that'll be done next.

Remove call to membership.update() in ping response. It was redundant

---

index.js
test/index-test.js

Not being able to pass these into `bootstrap()` is hampering the ability to diagnose cluster-level issues that occur on startup.

Pass joinRetryDelay and maxJoinAttempts into join

---

scripts/tick-cluster.js

- spawn generic ringpop processes (binaries or via interpreter). e.g.
```
tickcluster 10 path/to/binary/testpop
tickcluster 10 -i node path/to/main.js
tickcluster 10 --interpreter node path/to/main.js
```
where tickcluster is an alias for `alias tickcluster='node ~/code/ringpop/scripts/tick-cluster.js'`.
- Adds grid mode view. Press z to activate
- Also removed a bug where tickcluster crashes if you request status (type 's') directly after starting the cluster.
@jwolski, @danielheller

Wieger tick cluster go

---

examples/tchannel-forwarding.js
package.json
ringpop-handler.js
test/integration/index.js
test/integration/proxy-test.js
test/integration/tchannel-proxy-test.js
test/lib/alloc-ringpop.js
test/lib/bootstrap.js
test/lib/tchannel-proxy-cluster.js

This is an implementation of ringpop forwarding for
tchannel v2.
You can see the expected use case in the examples.
TODO: 
I suspect we do not want retries in RingpopHandler and
should rely on retries in either the client or in hyperbahn
itself. We currently have retries in HTTP forwarding because
we dont have retries in HTTP clients..
Adding early abort on checksum failure is possible but I should
probably carve out another transport header for it. Maybe
add "server checksum" or "sc" as a transport header.
If we do not implement early abort on checksum failure then
a request could in theory get forwarded forever because
infinite divergence or flappy-ness. Of course it will timeout
in tchannel itself but it would be nicer to have a UnexpectedError
telling you that its ringpop divergence …

Implement tchannel forwarding for node.

---

test/integration/proxy-test.js

This is a fix for the test that broke in between tchannel (as a devDependency) between 2.5.1 and 2.6.1. I confirmed with @jcorbin that the tchannel commit that git-bisect pointed at was intentional. Thankfully, this "problematic" commit neither breaks Ringpop nor TChannel, just a test (that was highly coupled to existing TChannel behavior). This closes all peer connections and induces a closed socket and makes the test pass.
@benfleis @danielheller @CorgiMan @Raynos

Close all peer connections to trigger socket closed response

---

package.json

This is a convenience that I needed after debugging a timer leak in our test suite. It makes sense to separate out this change from others.
@danielheller @CorgiMan @benfleis

Run integration tests

---

test/join-sender-test.js
test/lib/test-ringpop.js
test/membership-update-rollup-test.js
test/proxy_req_test.js
test/ringpop_alloc_error_test.js

Fixes for tests that weren't cleaning up their Ringpop instance. This left leaky timers and only became a problem because of upcoming flap damp scoring code. Trust me on this ;)
@benfleis @danielheller @CorgiMan

All sorts of leaky tests weren't properly cleaning up

---

package.json
ringpop-handler.js

Update to work past https://github.com/uber/tchannel/pull/1222 which shipped in TChannel 2.7.0.
r @jwolski

RingpopHandler: update RelayRequest usage for TChannel 2.7.0

---

lib/request-proxy/index.js
lib/request-proxy/send.js
test/request_proxy_test.js

@jwolski @markyen This allows ringpop-replicator to disable key lookups on retries, and hence fixes the following issue:
> Before retrying, ringpop looks up the destination for the given keys again, and if it finds the keys are
> now mapped to more than one destination, ringpop will return the "Destinations for proxied request 
> have diverged" error. This behavior is not compatible with replication because the lookup during 
> retries does not account for the replicas destinations.

add a skipLookupOnRetry request opt

---

config.js
index.js
lib/membership/index.js
lib/membership/member.js
package.json
scripts/tick-cluster.js
test/lib/test-ringpop.js
test/unit/config_test.js
test/unit/index.js
test/unit/member_test.js
test/unit/membership_test.js

This is the first of several PRs to come for flap damping. The first is damp scoring. A member in the membership list will be penalized for every update that is applied. When the damp score exceeds the configured damp suppress limit, an event will be emitted. Later, this event will initiate the damping subprotocol. (That's the next PR to come). The damp scores for all members decay exponentially, its periodicity governed by another configurable parameter. 
I left a few cheeky comments and added a few bells/whistles (like the separate Config object) to this PR to accompany the scoring. Don't mind them too much.
The test coverage is fairly reasonable.
Oh, and also... tick-cluster needed a bit of fixing. A member's damp score is now part of the returned stats. The way tick-cluster previously …

Flap damp scoring

---

lib/membership/index.js

Ringpop does not currently emit stats when a node explicitly changes the status of a member. This new stat is complementary to the `membership-update.*` stats that Ringpop emits when it observes an update that has been gossiped and applied.
@benfleis @danielheller @Raynos @CorgiMan

Add make-* stats

---

config.js
index.js
lib/swim/join-sender.js
package.json
server/protocol/join.js
test/integration/join-test.js
test/unit/config_test.js
test/unit/server/protocol/join_test.js

This is the start of a formal member blacklist. This prevents joins from 'unintended' members which are specifiable by a `memberBlacklist` config. Apps can choose arbitrary regexs for the blacklist.
Oh, and yes, this'll need to be back-ported, if services that desire this functionality cannot upgrade to 10.x.x.
@CorgiMan @danielheller @markyen @benfleis

Join blacklist to prevent unintended hosts from joining cluster

---

lib/swim/ping-req-sender.js
test/integration/swim-test.js

addresses: https://github.com/uber/ringpop-node/issues/167
Allow a 2-node cluster to split and generate proper suspect mark events, etc.,
and subsequent rejoins. Current code short circuits suspect logic, and will
never mark faulty or generate new checksum.
Since there is a test demonstrating that 2-node ping fail generates an error,
not sure if this is the correct/desired approach.

allow 2-node clusters to split and rejoin

---

client.js
index.js
lib/errors.js
lib/membership/index.js
lib/swim/join-sender.js
lib/trace/config.js
lib/trace/core.js
lib/trace/index.js
lib/trace/log.js
lib/trace/store.js
lib/trace/tchannel.js
lib/trace/types.js
lib/util.js
main.js
package.json
server/index.js
server/trace.js
test/lib/test-ringpop-cluster.js
test/trace-test.js

to tchannel or the given logger object.
event tracers allow a live ringpop system to dynamically foward internal
events to arbitrary events, creating space for ephemeral live event
analysis and diagnostics in running clusters.
see https://github.com/uber/ringpop/issues/139
This diff is *incomplete* -- tests are not added yet, and there are several open XXX questions for @jwolski (or others, wink wink @raynos) to consider addressing.

add basic trace feature to ringpop; currently support traces that output

---

index.js

r @jwolski @benfleis 
This is necessary for whoever needs to use channel to clean up before it is destroyed.

emit destroying message right before ringpop is destroyed

---

lib/membership/member.js
test/unit/member_test.js

Beginning work on next phase of flap damping. There'll be some small PRs for continuing improvement to codebase, but that are fairly unrelated to the task at hand. Here's the first. A helper function on the Member prototype to abstract away a Member's ID. This comes about as a result of indexing outstanding damp subprotocola by a Member's ID. I want to prevent anymore assumptions about what the ID is for obvious reasons.
Since this is so trivial, I'll likely self-merge.
@danielheller @CorgiMan @benfleis @thanodnl @mbrysa

Add Member::getId

---

index.js
server/index.js

More incidental cleanup from damp subprotocol work.
@uber/ringpop

Renamed legacy name RingPopTChannel to RingpopServer

---

index.js
lib/swim/gossip.js
server/admin/gossip.js

This pingMemberNow has been bothering me since the dawn of time. I had to take the plunge and get rid of it. Minor refactoring. Just moved some code around, leading to a more intuitive Gossip interface.
@uber/ringpop

Get rid of the dreadful pingMemberNow; make tick() part of gossip

---

client.js
index.js

More incidental cleanup. Take note that this is branched off of `renamed-ringpop-tchannel` branch and not master. The new damping subprotocol PR will make use of RingpopClient to fanout its damp score requests.
@uber/ringpop

Client can make use of subChannel passed into constructor

---

test/unit/dissemination-test.js
test/unit/hashring_test.js
test/unit/index-test.js
test/unit/join-response-merge-test.js
test/unit/join-sender-test.js
test/unit/membership-changeset-merge-test.js
test/unit/membership-iterator-test.js
test/unit/membership-set-listener-test.js
test/unit/membership-update-rollup-test.js
test/unit/proxy_req_test.js
test/unit/rbiterator_test.js
test/unit/rbtree_test.js
test/unit/request_proxy_test.js
test/unit/ring-test.js
test/unit/ringnode_test.js
test/unit/ringpop_alloc_error_test.js
test/unit/swim_test.js
test/unit/trace-test.js

The disorganization had gone unaddressed for far too long. This PR at least puts all straggler tests under the units folder.
@uber/ringpop

Make better sense out of the organization of the test suite

---

lib/membership/index.js
test/unit/member_test.js

This bug'll cause leaky listeners and unnecessary CPU churn when redundant updates are processed.
@uber/ringpop

Remove listener after evaluating update to prevent leaking listeners

---

lib/membership/index.js
lib/membership/update.js

This concretely defines Update types. Why this is need will make more sense in a PR still to come. In general, I think it's much better to explicitly define the shape of the updates that are transmitted as part of the gossip protocol.
@uber/ringpop

Add membership update types

---

server/admin/lookup.js

During the creation of the integration tests it came to my attention that the `/admin/lookup` endpoint was using the complete body as the key while the implementation in golang used the value provided in the `key` field of the body. This inconsistency made it impossible to test correctness of the lookup.
Looking in [`ringpop-admin`](https://github.com/uber/ringpop-admin/blob/master/lib/admin-client.js#L52-L54) (which I expect to be the only use of the lookup endpoint) revealed that sending a json object with a field `key` was the expected way to lookup a key.
This patch changes the `/admin/lookup/` endpoint in such a way that it will lookup the key for `your key` instead of `{key:"your key"}` when using `ringpop-admin lookup "host:port" --key "your key"`.
/cc @uber/ringpop

Parse the key from the body of /admin/lookup.

---

lib/on_membership_event.js
lib/on_ring_event.js
lib/ring/events.js
lib/ring/index.js
test/unit/index-test.js

Over in Hyperbahn, I would like to incrementally update sorted arrays of affine relay addresses to reduce the cost of updating the service proxy in response to ring changes. To that end, I would like to thread the arrays of added and removed servers through the event.
I’ve added this feature and altered the existing test to verify the intended added and removed hosts, initializing the test to reflect reality since, but please check…it does not match my intuition.
r @uber/ringpop @jwolski

Share arrays of added and removed addresses on ringChanged

---

config.js
index.js
lib/gossip/joiner.js
server/admin/member.js
test/integration/join-test.js
test/unit/config_test.js
test/unit/joiner_test.js

This is a quick hotfix to apply a backoff delay for the join process.
It'll backoff exponentially up to the max join delay (2 mins) in between each retry and try to join up to the max join duration (20 mins). Ringpop will flag the developer with an error when the join delay reaches its max. If join duration is exceeded, Ringpop'll still do nothing and just idle naively waiting for something to be done. A continuous joiner and refusing gossip communication are left for future PRs.
@uber/ringpop

Join duration w/ backoff

---

lib/gossip/joiner.js

This stat will give us a better idea about how successful the join fan-out is for all Ringpop-based applications.
@uber/ringpop

Stat number of retries performed during join process

---

config.js
index.js
lib/gossip/joiner.js
lib/gossip/ping-req-sender.js
lib/gossip/ping-sender.js
lib/logging/levels.js
lib/logging/logger_factory.js
lib/logging/module_logger.js
server/protocol/ping-req.js
test/lib/test-ringpop.js
test/unit/module_logger_test.js

Some apps like to log. Some apps don't. Some logs are nice to have for debugging. Some logs aren't. Module loggers allow different Ringpop components/modules to have individually configurable logging levels which are settable in the Ringpop constructor or over the /admin/config/set endpoints.
reviewers: @thanodnl @benfleis 
cc: @uber/ringpop

Module loggers w/ individually configurable levels

---

config.js
index.js
lib/lag_sampler.js
lib/on_config_event.js
lib/request-proxy/index.js
package.json
test/integration/proxy_test.js
test/lib/test-ringpop.js

This pull request applies backpressure at Ringpop's forwarding egress and ingress by using the number of inflight requests and the current event loop lag as the metric to use when evaluating how "overwhelmed" an application is.
reviewers: @thanodnl @danielheller
cc: @uber/ringpop @weikai77 @markyen @fuj

Backpressure at routing egress/ingress

---

lib/gossip/index.js

`this.ringpop.isPinging` was never set to true. 
`this.ringpop.gossip.isPinging` was never set to false.
At some point when I rearranged code, I'm sure I unintentionally broke this. It likely isn't showing up as any sort of production bug because it was originally put in place to make sure that tick-cluster's manual tick never ticked while a gossip tick was outstanding.
@uber/ringpop

Use the correct isPinging flags

---

config.js
lib/gossip/dissemination.js
lib/gossip/events.js
server/protocol/join.js
test/integration/admin_test.js
test/integration/gossip_test.js
test/integration/join-test.js
test/integration/proxy_test.js
test/lib/test-ringpop-cluster.js

If a node get's a join request, it no longer adds the joining node to the membership.
A node is therefor expected to disseminate it's own existance to the membership.
T212923

Let A Node Disseminate Itself After Join

---

client.js
config.js
index.js
lib/gossip/damper.js
lib/gossip/dissemination.js
lib/gossip/events.js
lib/gossip/index.js
lib/gossip/suspicion.js
lib/logging/logger_factory.js
lib/logging/module_logger.js
lib/membership/events.js
lib/membership/index.js
lib/membership/member.js
lib/membership/member_damp_score.js
lib/on_membership_event.js
main.js
request_response.js
server/protocol/damp_req.js
server/protocol/index.js
test/fixtures.js
test/lib/test-ringpop.js
test/unit/damper_test.js
test/unit/member_test.js
test/unit/module_logger_test.js
test/unit/server/protocol/damp_req_test.js

This PR introduces a Damper object which is responsible for:
* Tracking flappy members. A flappy member is one whose damp score exceeds the suppress limit.
* Periodically running a background damp timer that asks N-random other members for the damp scores of the same flappy members
* "Damping members" if the damp scores from the N-random members also exceed the suppress limit.
* Expiring damped members after members have been damped for greater than the suppression duration.
This PR does not actually 'treat' damped members other than logging an error when a Ringpop would have put a member in the damped status. The behavior to treat damped members will come in a later PR.
This PR is over 1200 lines. Take your time with it and of course, let me know if you have any high-level or fundamental …

Damping subprotocol

---

scripts/tick-cluster.js

Previously an exception would be thrown if stdin was not available at startup, e.g.:
```
dan-mbp-uber:tests dan$ ~/uber/projects/ringpop-node/scripts/tick-cluster.js ./../node_modules/ringpop/main.js <&-
[init] 09:56:24.110 tick-cluster started d: debug flags, g: gossip, j: join, k: kill, K: revive all, l: sleep, p: protocol stats, q: quit, s: cluster stats, t: tick
[cluster] 09:56:24.112 using 172.18.25.93 to listen
[init] 09:56:24.131 started 5 procs: 58433, 58434, 58435, 58436, 58437
/Users/dan/uber/projects/ringpop-node/scripts/tick-cluster.js:495
stdin.setRawMode(true);
^
TypeError: Object #<Socket> has no method 'setRawMode'
at main (/Users/dan/uber/projects/ringpop-node/scripts/tick-cluster.js:495:11)
at Object.<anonymous> …
```

Disable interactive mode if stdin is not available

---

scripts/tick-cluster.js

Adds the --interface option for specifying an interface that
ringpop instances should bind to.
Adds the --port option for specifying the base port that ringpop
instances will use.

Add options for interface/port in tick-cluster

---

config.js
lib/gossip/damper.js
lib/gossip/joiner.js
lib/gossip/ping-req-sender.js
lib/gossip/ping-sender.js
lib/request-proxy/send.js
test/unit/client_test.js

We've been told that TChannel does a lot less bookkeeping if retry limit is set to 0. Doing so for Ringpop, especially it's gossip protocol, should/will reduce that amount of bookkeeping done.
@uber/ringpop

Retry limit

---

docs/running_ringpop.md

This documentation is generated from a script that parses a CSV and turns it into a Markdown table. The long-term form of our stats "schema" likely won't be a CSV so I've not included that script in this branch.
@uber/ringpop

Add stats to Monitoring section of Running Ringpop docs

---

client.js
client_errors.js
client_request.js
client_request_errors.js
client_request_states.js
config.js
index.js
lib/logging/logger_factory.js
ringpop_errors.js
test/integration/admin_test.js
test/unit/client_request_test.js
test/unit/client_test.js

This pull requests creates a trackable request object (`ClientRequest`). Inflight requests (that have not had their callback called) are placed into `requestsById` in the `Client` object. There is a background timer (`wedgedTimer`) that periodically scans for "wedged requests" and cancels the request by preemptively invoking its callback. A wedged requests is canceled if it has been inflight for greater than `wedgedRequestTimeout`.
Internally, `ClientRequest` maintains a "state machine" at each step of the TChannel-send process. When a `ClientRequest` is canceled, its callback will be invoked by `Client`. The `ClientRequest` also makes sure that a callback isn't called multiple times by nullifying the callback after its first invocation.
@uber/ringpop

Track potentially wedged requests and cancel them

---

client.js
test/unit/client_test.js

unref'ing a setTimeout leaks memory:
Orig issue: https://github.com/nodejs/node-v0.x-archive/issues/8364
Changelog: https://github.com/nodejs/node/blob/v0.10.40-release/ChangeLog#L77
@uber/ringpop @Raynos

unref() has a memory leak; don't use it

---

package.json
test/integration/gossip_test.js
test/lib/tchannel-proxy-cluster.js

One test used to add '001' to the hostport to make it unreachable, tchannel doesn't allow huge port no.s anymore. The other test failed because: 'AssertionError: TChannel must listen on top channel'. Listening to the rootChannel fixed the test.

Update tchan to 3.6.13 and fix two tests that broke because of it.

---

index.js
lib/on_membership_event.js
lib/on_ring_event.js
lib/stats-periodic.js
package.json
test/integration/proxy_test.js
test/lib/alloc-ringpop.js
test/lib/timers-mock.js
test/unit/client_test.js
test/unit/damper_test.js
test/unit/stats-test.js
test/unit/trace-test.js

add {membership,ring}-checksum{,-periodic} stats for partition detection
replaced time-mock with timer-shim, to work with intervals, added small wrapper for trivial compatibility.
@uber/ringpop

T287803 ring.checksum stats

---

.jshintignore
.travis.yml
package.json
test/.gitignore
test/index.js
test/run-shared-integration-tests
test/travis

This PR adds an npm script `npm run test-shared-integration-tests`. This script runs the shared integration tests from the ringpop-common repository.
It also adds the running of these tests to Travis CI.

Run shared integration tests on Travis

---

lib/gossip/dissemination.js
package.json

The `git pre-commit` hooks are failing on `npm run jshint`. To prevent this happening in the future this PR adds `npm run jshint` to the travis target so CI will complain if source code does not pass `jshint`.
To make sure everything passes the `process` function is now declared before its use in `onJoin`.

Travis jshint

---

server/admin/index.js
server/admin/reload.js

Part of the feedback on #253 was to deprecate the `admin/reload`-endpoint.
The endpoint isn't used by ringpop-admin and, according to our internal metrics, has never been called in production.
Triggering a reload was probably useful during testing when the bootstrap file changed. With partition healing, we achieve a similar result in that the discover provider will be re-queried, except that it's automatic.

Deprecate "admin/reload"-endpoint

---

lib/gossip/index.js
lib/gossip/ping-sender.js
server/protocol/ping-req.js
test/integration/not-ready-test.js

To support partition healing we need to manually specify the changes sent during a ping-request (instead of gossiping the changes from `dissemination`). In this case we also don't need to update the membership-list.
Both changes are required to be able to send and retrieve changes without marking all the members as faulty before merging partitions.

Refactor ping-sender to support sendPingWithChanges

---

test/index.js

Due to an incorrect glob-syntax, the tests in `tests/unit/server` were not running.

Run tests in sub-directories of unit and integration as well

---

test/unit/gossip_test.js

`period` was renamed to `supectTimeout` in a previous commit.

Fix some timers in gossip unittests

---

lib/gossip/state_transitions.js
lib/membership/index.js
lib/membership/member.js
lib/on_membership_event.js
main.js
server/admin/member.js
test/run-shared-integration-tests
test/unit/dissemination-test.js
test/unit/gossip_test.js
test/unit/index-test.js
test/unit/membership_test.js

This adds the reaping faulty nodes on top of the tombstone wire compatibility (which is landed). It's very similar to the [Go implementation](https://github.com/uber/ringpop-go/pull/132) and includes the admin endpoint.

Implement reaping faulty nodes

---

lib/gossip/dissemination.js
server/protocol/join.js
test/integration/join-test.js
test/unit/dissemination-test.js

In the ringpop-go we renamed fullSync to MembershipAsChanges. This pull-request is doing the same thing in ringpop-node because that's better describing what the function does: returning the full membership as changes.

Rename Dissemination.fullSync to membershipAsChanges

---

config.js
lib/on_ringpop_event.js
lib/partition_healing/discover_provider_healer.js
test/unit/discover_provider_healer_test.js
test/unit/server/admin/partition_healing_test.js

Try to heal partitions periodically. By using a probability variable, on average `x` amount of nodes will try to perform the heal every `y` seconds (where `x` = `discoverProviderHealerBaseProbability`, and `y` = `discoverProviderHealerPeriod`). 
The defaults are 3 nodes every 30 seconds.

Periodical partition healing

---

config.js
index.js
lib/partition_healing/discover_provider_healer.js
lib/partition_healing/healer.js
lib/partition_healing/index.js
server/admin/index.js
server/admin/partition-healing.js
test/integration/gossip_test.js
test/integration/partition_healing_test.js
test/lib/gossip-utils.js
test/lib/test-ringpop-cluster.js
test/run-shared-integration-tests
test/unit/discover_provider_healer_test.js
test/unit/server/admin/partition_healing_test.js

Bring back partition healing (#264 and #265) that was reverted because they depended on the `async`-library (a dev-dependency).
The first commit (ce067bf8de1de57f40032d9aa139001d002c58f4) is a revert of the reversion of the 2 previous PR's, the second commit (8594894b83798f2d2c94bc6f7824b7639b43428c) removes the dependency on `async`.

Partition healing

---

discover-providers.js

Since discover-providers are using a callback to return the host list, the hosts-file could be able to read the file asynchronously.

Read hosts-file async

---

main.js

Add suspect, faulty and tombstone period flags so that integration tests can set a small faulty->tombstone period of 5 seconds while having a big faulty->tombstone period when running from tickcluster.

add suspect, faulty and tombstone period flags

---

lib/membership/member.js
test/unit/membership_test.js

When a gossip was received that would overwrite the state of the local node we overwrite this change with a reincarnated version of our self. However we used the source of the original change as the source for this change making it harder for the reincarnated change to reach the node that declared it a suspect in the first place.
This change will use the source and new reincarnation number of the local node for this new change. This prevents the reincarnation change to be filtered out in pings to the original source causing convergence to speedup and potentially prevent fullsyncs from happening.

When creating the change for reincarnation use your self as the source.

---

lib/membership/member.js
test/run-shared-integration-tests
test/unit/membership_test.js

This change will add a check for the incarnation number before reincarnating a node by incrementing its incarnation number. This reduces the number of gossips being sent in the case of reincarnation. Which will result in faster memberlist convergence.

Fix double reincarnation

---

lib/membership/index.js
lib/membership/member.js
lib/membership/update.js
test/unit/discover_provider_healer_test.js

Change the update-constructor to take a subject and source.
To be able to document everything correctly, I had to:
- add `@enum` to `Member.Status`,
- Add an interface for member (`IMember`)

Status refactor 5: Change update constructor

---

lib/membership/index.js
test/unit/damper_test.js
test/unit/dissemination-test.js
test/unit/gossip_test.js
test/unit/index-test.js
test/unit/membership-iterator-test.js
test/unit/membership_test.js
test/unit/server/protocol/damp_req_test.js

Since it's not allowed by the SWIM protocol for a node to change a member's status to `alive` or `leave`,  let's remove these methods. Tests can use the generic `makeChange`-function.

Status refactor 4: Remove makeLeave and makeAlive

---

lib/membership/index.js
lib/membership/update.js
test/unit/discover_provider_healer_test.js

Due to the `makeChange`-refactor, `LeaveUpdate` isn't used anymore: it's a normal update with a leave-status. Let's remove this now obsolete update.

Status refactor 3: Remove the now unused “LeaveUpdate”

---

lib/membership/index.js
lib/membership/member.js
lib/membership/update.js
test/unit/damper_test.js
test/unit/discover_provider_healer_test.js
test/unit/dissemination-test.js
test/unit/gossip_test.js
test/unit/index-test.js
test/unit/membership-iterator-test.js
test/unit/membership_test.js
test/unit/server/protocol/damp_req_test.js

There’s a lot of code duplication among the different `make{Alive,Faulty,Leave,Suspect,Tombstone}`-functions. This PR adds a `makeChange`-function that does all the work of the previous `make*Status*`-functions.
_Note: this is the second PR of a serie of refactors_

Status refactor 2: Refactor make* to use common method

---

index.js
lib/membership/index.js
lib/membership/member.js
lib/membership/update.js
server/admin/member.js
test/integration/proxy_test.js
test/lib/test-ringpop.js
test/unit/damper_test.js
test/unit/discover_provider_healer_test.js
test/unit/dissemination-test.js
test/unit/gossip_test.js
test/unit/index-test.js
test/unit/member_status_test.js
test/unit/member_test.js
test/unit/membership-iterator-test.js
test/unit/membership_test.js
test/unit/server/protocol/damp_req_test.js

Use a in-memory object to represent once local state. This makes the code path that updates the local state more robust. Instead of changing the state of the current node by updating it using updates, we just change the `localMember`. 
Whenever a gossip comes in changing the current state, we can always "counter-gossip" with the current state.
_Note: this is the first PR of a serie of refactors:_

Status refactor 1: Refactor membership to use localMember as the source of truth

---

index.js
package.json
test/integration/proxy_test.js

The hammock library is used in the ringpop proxy code
and had some performance issues in response buffering.
These are fixed in the latest version of hammock
r: @thanodl @motiejus @mennopruijssers

Update version of hammock for perf boost

---

lib/partition_healing/discover_provider_healer.js
test/unit/discover_provider_healer_test.js

Since we now support a self declared faulty on the local member, during partition healing we need to explicitly exclude ourself from the list of targets during partition healing.
previously this was implied because the local member always changed it's status to `alive`.

Disable healing on self

---

config.js
index.js
lib/self-evict.js
main.js
test/run-shared-integration-tests
test/unit/index-test.js
test/unit/self-evict-test.js

This PR adds a way to add self-eviction: marking the local member faulty before shutdown. 
It adds two functions to ringpop's public API:
- `registerSelfEvictHooks`: Provide a way to register hooks
- `selfEvict`: initiate the self eviction process
TODO in seperate PR(s):

[self-evict 1] Support self eviction as a way of graceful shutdown

---

lib/self-evict.js
test/unit/self-evict-test.js

After merging #299, #300 and #301, a test in ringpop-serial broke (probably bad merge); this fixes it.
Also added some extra type-checking on the hooks (`isFunction`).

Fix for self-eviction hooks

---

index.js
lib/request-proxy/index.js
test/unit/request_proxy_test.js

Currently ringpop can be configured to compare the hashring when a request is forwarded and drop the request if the hashrings are inconsistent. This causes a lot of requests that are actually forwarded to the correct node to fail, resulting in a lot of timeout and errors on rolling restarts.
The PR will add the possibility to loosen the requirement from ring consistency to key consistency eg. if the key from the forwarded request is believed to be owned by the receiving node based on a hashring lookup it will execute the request. When this happen both the forwarder and the receiver of the forwarded request agree on the key ownership for the key to the receiving end.
This showed a huge improvement in performance of a ringpop application during a rolling restart.

[Feature] Key consistent forwarding

---

lib/gossip/state_transitions.js
lib/on_membership_event.js
test/run-shared-integration-tests
test/unit/membership_test.js
test/unit/state_transistion_test.js

This PR fixes an issue where transition timers (`faulty` -> `tombstone`) were not scheduled correctly if the membership during a `join`-response contains a `faulty`-member. Instead of duplicating the code that schedules the timers, a method is extracted from the gossip handler and used on the `set`-event (emitted after the initial join).

Fix: Initial transition timers

---

lib/ring/index.js
lib/ring/rbtree.js
test/unit/rbiterator_test.js
test/unit/rbtree_test.js
test/unit/ringnode_test.js

This is the first part of the fix for consistent hashring lookups on hash collisions where we abstract the RBTree to not care about the datatypes stored. Comparison is done by a comparator function.
This will help in later stages where the `key` can contain more data points instead of the hash.

[Fix] Consistent hash ring lookups 1 / Use comparator function

---

lib/ring/index.js
test/lib/int-comparator.js
test/unit/hashring_test.js
test/unit/rbiterator_test.js
test/unit/rbtree_test.js

This PR changes the key in the RBTree from the hash to a replica point in preparation for a better compare function.

[Fix] Consistent hash ring lookups 2 / Use replicaPoints as RBTree key

---

lib/ring/index.js
test/unit/hashring_test.js

With the two previous PR's in place, the stage is set for the actual fix. By comparing not just the hash but also the addresses of two replica points in the hash ring, we know for sure that the order  is guaranteed -- even when there are hash collisions.

[Fix] Consistent hash ring lookups 3 / consistent lookups on hash collisions

---

package.json

Simple change bumps hammock to do the right thing in node versions later than 0.10. This module is used to do request forwarding and needs to be corrected for changes in behavior to req/res headers and some streams related issues.

update hammock for node4+ support
